name: rahisisha
description: A business management app for small businesses
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0
  flutter_localizations:
    sdk: flutter
  # For state management
  provider: ^6.0.0

  # For local storage
  shared_preferences: ^2.0.13
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  google_fonts: ^6.0.0
  image_picker: ^1.0.0
  file_picker: ^6.0.0
  share_plus: ^7.0.0
  connectivity_plus: ^5.0.2
  pdf: ^3.11.3
  printing: ^5.14.2
  uuid: ^4.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/white.png
    - assets/images/blue.png

  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/blue.png" # For iOS
  adaptive_icon_foreground: "assets/images/launch.jpeg" # For Android adaptive foreground
  adaptive_icon_background: "#0xFF1976D2" 
  remove_alpha_ios: true

  
  

flutter_intl:
  enabled: true